version: '3.0'

services:
  grafana:
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.4.7}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/tarent-jira-datasource
